project:
  type: website

website:
  #title: Portfolio
  navbar:
    pinned: true
    background: primary
    search: true
    right:
      - icon: twitter
        text: Twitter
        href: https://twitter.com/sergiolois
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/slois/
      - icon: github
        text: Github
        href: https://github.com/slois
    left: 
      - index.qmd
      - text: "About me"
        menu:
          - text: Who am I?
            href: about.qmd
          - posts/thesis/mythesis.qmd
          - posts/publications/publications.qmd
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: G-CV1HE8NZ9Y
    anonymize-ip: true
  page-footer: "Copyright 2022, Sergio Lois"
format:
  html:
    theme: slate #flatly
    css: styles.css

editor: visual

execute:
  freeze: true
